version: '3'
services:
  back:
    image: niphto/myapp-back:latest
    ports:
      - "5000:5000"
    environment:
      CURRENT_ENVIRONMENT: development
    volumes:
      - back-data:/app/data

  front:
    image: aimalvin/myapp-front:latest
    ports:
      - "80:80"
    environment:
      WS_BACK_URL: "http://host.docker.internal:5000"
